name: BlackParrot Tests

on:
  workflow_call:

env:
  GHA_CUSTOM_LINE_PREFIX: "▌"

jobs:
  blackparrot_synth:
    name: BlackParrot (synthesis)
    runs-on: [self-hosted, Linux, X64]
    container: ubuntu:jammy
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up common Ubuntu configuration
        run: ./.github/scripts/set-up-common-ubuntu-configuration.sh

      - name: Install dependencies
        run: |
          apt-get update -q
          apt-get install -y \
              ant \
              build-essential \
              cmake \
              default-jre \
              flex \
              git \
              google-perftools \
              libfl-dev \
              libftdi1-dev \
              libgoogle-perftools-dev \
              ninja-build \
              python3 \
              python3-dev \
              python3-pip \
              srecord \
              swig \
              tcl-dev \
              tclsh \
              uuid \
              uuid-dev \
              ;
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

      - name: Checkout submodules
        run: |
          git submodule update --depth 1 --init --recursive \
              third_party/black_parrot \
              ;
          git submodule update --depth 1 --init \
              third_party/black_parrot_tools \
              third_party/black_parrot_sdk \
              ;

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries

      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xf binaries.tar

      - name: Build & Test
        run: |
          pip install virtualenv
          make -C uhdm-tests uhdm/yosys/synth-blackparrot-build TEST=black-parrot \
              ENABLE_READLINE=0 PRETTY=0 -j $(nproc)

      - uses: actions/upload-artifact@v2
        with:
          name: bp_e_bp_unicore_cfg.edif
          path: uhdm-tests/build/bp_e_bp_unicore_cfg.edif

      - name: Upload load graphs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: plots
          path: |
            **/plot_*.svg
