name: VeeR Tests

on:
  workflow_call:

env:
  GHA_CUSTOM_LINE_PREFIX: "▌"

jobs:
  veer_synth:
    name: VeeR-EH1 (synthesis)
    runs-on: [self-hosted, Linux, X64]
    container: ubuntu:jammy
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up common Ubuntu configuration
        run: ./.github/scripts/set-up-common-ubuntu-configuration.sh

      - name: Install dependencies
        run: |
          apt-get update -q
          apt-get install -y \
              ant \
              build-essential \
              cmake \
              default-jre \
              flex \
              git \
              google-perftools \
              libfl-dev \
              libftdi1-dev \
              libgoogle-perftools-dev \
              ninja-build \
              python3 \
              python3-dev \
              python3-pip \
              srecord \
              swig \
              tcl-dev \
              tclsh \
              uuid \
              uuid-dev \
              ;
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
